inherit_from: .rubocop_todo.yml

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
